openapi: 3.0.3
info:
  title: PiaSDK required endpoints
  description: >-
    Some useful links:

    -
    [Netaxept-iOS-SDK](https://github.com/Nets-mobile-acceptance/Netaxept-iOS-SDK/tree/master/ReactNative)

    - [Netaxept Sample
    Backend](https://github.com/Nets-mobile-acceptance/Netaxept-Sample-Backend)

    -
    [Netaxept-Payment-Flow](https://nets-mobile-acceptance.github.io/Netaxept-iOS-SDK/11-basic-payment-flow.html)
    [FAQ](https://nets-mobile-acceptance.github.io/Netaxept-iOS-SDK/53-faqs.html#2-why-do-i-need-to-provide-a-redirecturl-in-register-call-and-in-the-sdk-what-are-they-used-for)
  version: 1.0.0
tags:
  - name: payment
paths:
  /GetTransactionId:
    get:
      tags:
        - payment
      summary: This should register payment in backend and return the paymentId
      operationId: getPaymentId
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionDTO'
        '400':
          description: Invalid status value
  /PaymentDetailsByQuoteId:
    get:
      tags:
        - payment
      summary: We need payment details for triggering PiaSDK payment process
      operationId: paymentDetails
      parameters:
        - name: quoteId
          in: query
          description: Quote id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDetailsDTO'
        '400':
          description: Invalid status value
components:
  schemas:
    TransactionDTO:
      type: object
      properties:
        transactionId:
          type: string
          example: '123456'
        redirectUrl:
          type: string
          description: If you don’t provide the SDK the same redirectUrl that has been used in the registerCall, the payment authorization will be successful, but the result delivered to your application will be error - GENERIC_ERROR
          example: seijfa://
    PaymentDetailsDTO:
      type: object
      properties:
        amount:
          type: integer
          format: int64
          example: 120
        currency:
          type: string
          example: SEK
        merchantId:
          type: string
          description: >-
            Your merchant number (also known as merchant ID) can be found in
            Easy Portal and is displayed at the top of the page. A merchant
            number can only contain digits.
          example: 12004500
